### ISSUE TITLE
[建议] 在启动前使用natter-check.py进行环境检测

### ISSUE THREAD

**Issue by emptysuns** [taskmgr818/hath-with-natter#5]
我看你好像只把natter.py给搬过来了
它其实是有一个check的工具的: https://github.com/MikeWang000000/Natter/tree/master/natter-check

如果不是nat1可以直接exit，因为有些人的设备是开着upnp但是没有公网ip的，这时会一直卡循环 (比如我

顺便一个建议，在`requirements.txt`加入一个httpx[socks]的包，就可以使用socks5进行代理了，httpx只能使用http代理有点鸡肋
```
proxy:
  # 是否使用代理与e-hentai.org通信
  enable: True
  # 是否使用代理下载缓存
  cache_download: False
  url: socks5://127.0.0.1:8081
```
